/**
 * Grade Entity
 *
 * Represents a grade assigned to a student for a specific evaluation item.
 * Contains the grade value and optional comments.
 *
 * @module GradeEntities
 * @grades Entity
 */

/**
 * Entity representing a grade
 *
 * A grade is associated with a specific student and evaluation item,
 * and includes a numeric value and optional comments.
 *
 * @class Grade
 * @grades Model
 */
export class Grade {
  /**
   * Unique identifier for the grade
   * Generated by the database when the grade is created
   *
   * @grades Property
   */
  id: string;

  /**
   * ID of the student this grade belongs to
   * References a Student entity
   *
   * @grades Property
   */
  studentId: string;

  /**
   * ID of the evaluation item this grade belongs to
   * References an EvaluationItem entity
   *
   * @grades Property
   */
  evaluationItemId: string;

  /**
   * Numeric value of the grade
   * Typically a score within the range defined by the evaluation item
   *
   * @grades Property
   */
  value: number;

  /**
   * Optional comments about the grade
   * Can include feedback, observations, or justifications
   *
   * @grades Property
   */
  comments?: string;

  /**
   * Date when the grade was created
   * Auto-generated by the database
   *
   * @grades Property
   */
  createdAt: Date;

  /**
   * Date when the grade was last updated
   * Auto-generated by the database
   *
   * @grades Property
   */
  updatedAt: Date;
}
