services:
  siag-api-prod:
    container_name: siag-api-prod
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    image: siag-api-prod
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: ["sh", "-c", "npx prisma migrate deploy && ts-node src/scripts/import-universities.ts && npm run start:prod"]
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped