/**
 * Student Response DTO
 *
 * Data Transfer Object for returning student data in API responses.
 * Represents the structure of student data returned to clients.
 *
 * @module StudentDTOs
 * @students DTO
 */
import { ApiProperty } from '@nestjs/swagger';

/**
 * DTO for formatting student data in API responses
 *
 * Contains all student properties including system-generated fields
 * like ID and timestamps.
 *
 * @class StudentResponseDto
 * @students Response
 */
export class StudentResponseDto {
  /**
   * Unique identifier for the student
   * Generated by the database
   *
   * @students Property
   */
  @ApiProperty({
    description: 'ID único do estudante',
    example: '550e8400-e29b-41d4-a716-446655440000',
  })
    id: string;

  /**
   * Full name of the student
   *
   * @students Property
   */
  @ApiProperty({
    description: 'Nome completo do estudante',
    example: 'João da Silva',
  })
    name: string;

  /**
   * Email address of the student (optional)
   *
   * @students Property
   */
  @ApiProperty({
    description: 'E-mail do estudante (opcional)',
    example: 'joao.silva@exemplo.com',
    required: false,
  })
    email?: string;

  /**
   * Registration number/identifier of the student
   *
   * @students Property
   */
  @ApiProperty({
    description: 'Número de matrícula do estudante',
    example: '20230001',
  })
    registration: string;

  /**
   * ID of the class this student belongs to
   * References a Class entity
   *
   * @students Property
   */
  @ApiProperty({
    description: 'ID da turma à qual o estudante pertence',
    example: '550e8400-e29b-41d4-a716-446655440001',
  })
    classId: string;

  /**
   * Date when the student was created
   * Auto-generated by the database
   *
   * @students Property
   */
  @ApiProperty({
    description: 'Data de criação do registro do estudante',
    example: '2023-01-15T14:30:00.000Z',
  })
    createdAt: Date;

  /**
   * Date when the student was last updated
   * Auto-generated by the database
   *
   * @students Property
   */
  @ApiProperty({
    description: 'Data da última atualização do registro do estudante',
    example: '2023-01-15T14:30:00.000Z',
  })
    updatedAt: Date;
}
