/**
 * Unit Entity
 *
 * Represents a unit (academic period or evaluation block) within a class,
 * such as a bimester, trimester, or semester, that contains evaluation items.
 *
 * @module UnitEntities
 * @units Entity
 */
import { ITypeFormula } from '@/modules/classes/domain/entities/class.entity';

/**
 * Entity representing a unit within a class
 *
 * A unit is a subdivision of a class, containing evaluation items and grades.
 * Units have names like "First Bimester" and can have their own grade calculation formulas.
 *
 * @class Unit
 * @units Model
 */
export class Unit {
  /**
   * Unique identifier for the unit
   * Generated by the database when the unit is created
   *
   * @units Property
   */
  id?: string;

  /**
   * Name of the unit
   * Examples: "Unidade 1", "First Bimester", "Midterm Period"
   *
   * @units Property
   */
  name: string;

  /**
   * ID of the class this unit belongs to
   * References a Class entity
   *
   * @units Property
   */
  classId: string;

  /**
   * Custom formula for calculating the unit average
   * Only used when typeFormula is 'personalized'
   *
   * @units Property
   */
  averageFormula?: string;

  /**
   * Type of formula used for grade calculation
   * 'simple' uses a simple average, 'personalized' uses a custom formula
   *
   * @units Property
   */
  typeFormula: ITypeFormula = 'simple';

  /**
   * Date when the unit was created
   * Auto-generated by the database, unless explicitly provided
   *
   * @units Property
   */
  createdAt?: Date;

  /**
   * Date when the unit was last updated
   * Auto-generated by the database
   *
   * @units Property
   */
  updatedAt?: Date;

  /**
   * Creates a new Unit entity
   *
   * @param {Object} props - Unit properties
   * @param {string} [props.id] - Optional unit ID
   * @param {string} props.name - Unit name
   * @param {string} props.classId - ID of the parent class
   * @param {string} [props.averageFormula] - Optional custom formula
   * @param {Date} [props.createdAt] - Optional custom creation date
   *
   * @units Constructor
   */
  constructor(props: Omit<Unit, 'updatedAt' | 'typeFormula'>) {
    Object.assign(this, props);

    // Se averageFormula estiver definido, definir typeFormula como 'personalized', caso contrário como 'simple'
    if (props.averageFormula) {
      this.typeFormula = 'personalized';
    } else {
      this.typeFormula = 'simple';
    }
  }
}
