/**
 * Grade Response DTO
 *
 * Data Transfer Object for returning grade data in API responses.
 * Represents the structure of grade data returned to clients.
 *
 * @module GradeDTOs
 * @grades DTO
 */
import { ApiProperty } from '@nestjs/swagger';

/**
 * DTO for formatting grade data in API responses
 *
 * Contains all grade properties including system-generated fields
 * like ID and timestamps.
 *
 * @class GradeResponseDto
 * @grades Response
 */
export class GradeResponseDto {
  /**
   * Unique identifier for the grade
   * Generated by the database
   *
   * @grades Property
   */
  @ApiProperty({
    description: 'ID único da nota',
    example: '550e8400-e29b-41d4-a716-446655440000',
  })
    id: string;

  /**
   * ID of the student this grade belongs to
   * References a Student entity
   *
   * @grades Property
   */
  @ApiProperty({
    description: 'ID do estudante ao qual a nota pertence',
    example: '550e8400-e29b-41d4-a716-446655440001',
  })
    studentId: string;

  /**
   * ID of the evaluation item this grade belongs to
   * References an EvaluationItem entity
   *
   * @grades Property
   */
  @ApiProperty({
    description: 'ID do item de avaliação ao qual a nota pertence',
    example: '550e8400-e29b-41d4-a716-446655440002',
  })
    evaluationItemId: string;

  /**
   * Numeric value of the grade
   * Typically a score within the range defined by the evaluation item
   *
   * @grades Property
   */
  @ApiProperty({
    description: 'Valor da nota (entre 0 e 10)',
    example: 8.5,
    minimum: 0,
    maximum: 10,
  })
    value: number;

  /**
   * Optional comments about the grade
   * Can include feedback, observations, or justifications
   *
   * @grades Property
   */
  @ApiProperty({
    description: 'Comentários sobre a nota',
    example: 'Excelente participação em sala de aula',
    required: false,
    nullable: true,
  })
    comments?: string;

  /**
   * Date when the grade was created
   * Auto-generated by the database
   *
   * @grades Property
   */
  @ApiProperty({
    description: 'Data de criação do registro da nota',
    example: '2023-01-15T14:30:00.000Z',
  })
    createdAt: Date;

  /**
   * Date when the grade was last updated
   * Auto-generated by the database
   *
   * @grades Property
   */
  @ApiProperty({
    description: 'Data da última atualização do registro da nota',
    example: '2023-01-15T14:30:00.000Z',
  })
    updatedAt: Date;
}
